### ISSUE TITLE
온점(.) 오류

### ISSUE THREAD

**Issue by composite** [theeluwin/textrankr#2]
재밌고 대단한 프로젝트를 개발하셨군요.
본론으로, 철쭉 위키백과를 인용하여 실험해봤습니다.

> 키는 2~5m쯤 되며 산에서 흔히 자란다.[2] 나무껍질은 회색 또는 회백색이고 세로로 불규칙하게 갈라진다. 어린 가지와 꽃자루는 끈끈하다.[1] 어린 가지에 선모가 있으나 점점 없어진다.[3] 잎은 거꾸로 된 달걀 모양이거나 넓은 타원 모양이고 털이 있다. 길이는 4~7 cm 정도이고, 너비는 1.5~2.5 cm 정도이며 보통 어긋나지만, 가지 끝에서는 4~5개씩 모여 난다.[2] 꽃은 4~5월에 연한 분홍색으로 잎이 나면서 피며 산형꽃차례를 이룬다. 꽃부리는 지름 5-8㎝의 깔때기 모양이며 5개로 갈라지는데, 위쪽 3개의 열편에 적갈색 반점이 있다. 수술은 10개이며 길이가 서로 다르고 암술은 1개이다. 열매는 삭과이며 길이 1.5㎝ 정도의 긴타원형 달걀꼴로 10월에 익는다.[3] 철쭉을 먹이식물로 하는 곤충으로는 극동등에잎벌의 애벌레가 있는데, 철쭉 잎 속에 알을 낳는다.

3줄요약 시 아래와 같은 결과가 나오는군요.

> 길이는 4~7 cm 정도이고, 너비는 1
> 2.5 cm 정도이며 보통 어긋나지만, 가지 끝에서는 4~5개씩 모여 난다
> 수술은 10개이며 길이가 서로 다르고 암술은 1개이다

여기서 첫줄 너비 부분 뒤에 1에서 멈춰 있는데, 의도한 결과라면 1.5~2.5cm 라고 나오고자 하는 게 맞다면 온점(.)에서 잘린 듯 합니다.

참여는 하고 싶은데 파이썬 잼병이라... 나름대로 보고 있습니다. 그럼 즐코.

**Comment by theeluwin** [comment]
으음 사실 지금은 문장 구분을 rule-based로 하고 있어서 대부분 문제가 생길겁니다.. 이를 꼬꼬마 형태소 분석기가 학습한 문장 구분 태그로 구별하면 정확도는 올라가지만 현재는 그렇게 하면 온전한 문장이 유지되지 않는 문제가 발생하여 당분간은 rule-based를 계속 써야할듯 합니다.

**Comment by theeluwin** [comment]
정규식 바꿔서 숫자.숫자 의 경우는 split 하지 않도록 했습니다.
