### ISSUE TITLE
Mac에서 실행 시 자바 런타임을 찾을 수 없는 문제

### ISSUE THREAD

**Issue by suminb** [theeluwin/textrankr#5]
맥(Sierra 10.12.1)을 사용하고 있는데, 다음과 같은 코드를 실행하면

    from textrankr import TextRank

다음과 같은 오류 메세지가 나옵니다.

    No Java runtime present, requesting install.

![image](https://cloud.githubusercontent.com/assets/136119/20247302/28be50fc-aa0c-11e6-8f82-516239a46f1e.png)

[KoNLPy에서 제가 보고했던 문제](https://github.com/konlpy/konlpy/issues/76)와 마찬가지로 Java 1.8의 버그인 것으로 추정됩니다. 다음과 같이 `JAVA_HOME` 환경 변수를 설정하면 문제 없이 동작합니다.

    export JAVA_HOME=$(/usr/libexec/java_home)

참고로 저의 시스템에는 Java 1.8.0-66이 설치되어있습니다.

    ➜  ~ java -version
    java version "1.8.0_66"
    Java(TM) SE Runtime Environment (build 1.8.0_66-b17)
    Java HotSpot(TM) 64-Bit Server VM (build 25.66-b17, mixed mode)

**Comment by theeluwin** [comment]
konlpy를 필요한 경우에만 쓰도록 바꿨습니다 (0.7)
